<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <RootNamespace>Mute</RootNamespace>
    <AssemblyName>Mute_0_38_0</AssemblyName>
    <ReleaseVersion>0.38.0</ReleaseVersion>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TShock" Version="5.2.4" />
  </ItemGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
