<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Mute</RootNamespace>
    <AssemblyName>Mute_0_38_0</AssemblyName>
    <ReleaseVersion>0.38.0</ReleaseVersion>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>

    <Reference Include="TerrariaServer">
		<HintPath>../../tshock_4.3.24/TerrariaServer.exe</HintPath>
    </Reference>
    <Reference Include="TShockAPI">
		<HintPath>../../tshock_4.3.24/ServerPlugins/TShockAPI.dll</HintPath>
    </Reference>

    <Reference Include="OTAPI">
        <HintPath>../../tshock_4.3.24/OTAPI.dll</HintPath>
    </Reference>

  </ItemGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
